---
title: "Home"
author: "Jacob Ford DCHC MPO"
date: "4/5/2021"
output: html_document
---

This document details the conversion the Piedmont Authority for Regional Transportion (PART) Triad Transportion Model input data into the TRMG2 Model. Expansion into Alamance County, and expanded coverage on the border of Orange County in Mebane, is a novel component of the TRMG2. The new coverage area, including Mebane and surrounding areas, has historically been covered by the Triad Model, so the existing network and demographic data was utilized to eliminate duplicative data collection processes. 

The following tabs provide addition information on how the Triad Model's TAZ structure, Land Use and Socioeconomic data, and highway network were converted into the TRMG2. 

Information regarding the Triad Model can be found [on the PART website](https://www.partnc.org/228/Regional-Travel-Demand-Model), in addition information regarding the land use and SE input data can be found [here](http://www.ncampo.org/documents/Toolkits_20130515-1515_Kim.pdf)


```{r, echo=FALSE, message=FALSE, warning=FALSE, results = 'hide'}
library(dplyr)
library(ggplot2)
library(leaflet)
library(tcadr)
library(sf)
library(xlsx)
library(readxl)
library(plotly)
library(sf)
library(dplyr)
library(tidygeocoder)
library(leaflet)
library(rgdal)
library(dplyr)
library(rmarkdown)
library(crosstalk)
library(lubridate)
library(htmltools)
library(RColorBrewer)

```

