---
title: "taz"
author: "Jacob Ford DCHC MPO"
date: "4/5/2021"
output: html_document
---


```{r, echo=FALSE, message=FALSE, warning=FALSE, results = 'hide'}
library(dplyr)
library(ggplot2)
library(leaflet)
library(tcadr)
library(sf)
library(xlsx)
library(readxl)
library(plotly)
library(sf)
library(dplyr)
library(tidygeocoder)
library(leaflet)
library(rgdal)
library(dplyr)
library(rmarkdown)
library(crosstalk)
library(lubridate)
library(htmltools)
library(RColorBrewer)

```

For TAZ conversion, only the conversion only concerned a certain number of Triad TAZs in Alamance and Mebane counties. 

```{r, echo=FALSE, message=FALSE, warning=FALSE, results = 'hide'}
triad_taz <- st_read("C:/Users/JacobFo/OneDrive - City of Durham/TRM G2/Alamance Expansion/Triad Model/Triad_TAZ.shp")

trm_taz <- st_read("C:/Users/JacobFo/OneDrive - City of Durham/TRM G2/Alamance Expansion/Triad Model/TRMG2_TAZ.shp")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

map <- leaflet(data=triad_taz) %>%
  setView(-79.26, 36.05, zoom=11) %>%
  addProviderTiles(providers$CartoDB.Positron)%>%
  addPolygons(data=triad_taz,
              group="Triad",
              color="black",
              fillColor = "lightgrey",
              weight=0.8,
             # fill=NA,
              dashArray = c("5,5"),
              popup=paste("Triad TAZ ID: ", triad_taz$TAZ)) %>%
  addPolygons(data=trm_taz,
              group="TRM",
              color="green",
              popup=paste("TRMG2 TAZ ID: ", trm_taz$ID1)) %>%
  addLayersControl(overlayGroups = c("Triad", "TRM"))

map

```

